name: Prestashop Release ZIP Validator

on: [pull_request]

jobs:
  prestashop-zip-validator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
        env:
          runner: self-hosted

      - name: Verify PHP Installation
        run: php -v

      - uses: "ramsey/composer-install@v3"

      - name: Create Release ZIP
        id: create-release
        run: bin/create-release-zip.sh

#      - name: Run Prestashop Validator
#        id: prestashop-validator
#        run: php bin/validate_zip.php mercadopago.zip
#        env:
#          VALIDATOR_API_KEY: ${{ secrets.VALIDATOR_API_KEY }}
